# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

C_anc_recon <- function(Y, anc, des, edge_vec, nedge, nvar, nspecies) {
    .Call('_Rphylopars_C_anc_recon', PACKAGE = 'Rphylopars', Y, anc, des, edge_vec, nedge, nvar, nspecies)
}

C_anc_recon_rates <- function(Y, anc, des, edge_vec, nedge, nvar, nspecies, REML) {
    .Call('_Rphylopars_C_anc_recon_rates', PACKAGE = 'Rphylopars', Y, anc, des, edge_vec, nedge, nvar, nspecies, REML)
}

try_inv <- function(M, nvar) {
    .Call('_Rphylopars_try_inv', PACKAGE = 'Rphylopars', M, nvar)
}

inv_subset <- function(mat_to_inv, subset_list) {
    .Call('_Rphylopars_inv_subset', PACKAGE = 'Rphylopars', mat_to_inv, subset_list)
}

mat_to_pars2 <- function(M, nvar, diag) {
    .Call('_Rphylopars_mat_to_pars2', PACKAGE = 'Rphylopars', M, nvar, diag)
}

pars_to_mat <- function(pars, nvar, diag, log_chol = 1L, mod_chol = 1L) {
    .Call('_Rphylopars_pars_to_mat', PACKAGE = 'Rphylopars', pars, nvar, diag, log_chol, mod_chol)
}

calc_OU_len <- function(heights, edge_mat, des_order, nedge, P, lambda, sigma, anc, des, nvar, nspecies) {
    .Call('_Rphylopars_calc_OU_len', PACKAGE = 'Rphylopars', heights, edge_mat, des_order, nedge, P, lambda, sigma, anc, des, nvar, nspecies)
}

tp <- function(L, R, Rmat, mL, mR, pheno_error, edge_vec, edge_ind, ind_edge, parent_edges, pars, nvar, phylocov_diag, nind, nob, nspecies, nedge, anc, des, REML, species_subset, un_species_subset, subset_list, ind_list, tip_combn, is_edge_ind, fixed_mu, OU_len, phylocov_fixed, phenocov_fixed, phenocov_list, is_phylocov_fixed = 0L, is_phenocov_fixed = 0L, OU_par = 0L, ret_level = 1L, use_LL = 0L, is_phenocov_list = 0L) {
    .Call('_Rphylopars_tp', PACKAGE = 'Rphylopars', L, R, Rmat, mL, mR, pheno_error, edge_vec, edge_ind, ind_edge, parent_edges, pars, nvar, phylocov_diag, nind, nob, nspecies, nedge, anc, des, REML, species_subset, un_species_subset, subset_list, ind_list, tip_combn, is_edge_ind, fixed_mu, OU_len, phylocov_fixed, phenocov_fixed, phenocov_list, is_phylocov_fixed, is_phenocov_fixed, OU_par, ret_level, use_LL, is_phenocov_list)
}

EM_Fels2008 <- function(pics, vars, phylocov, phenocov, nvar, phylocov_fixed, phenocov_fixed, is_phylocov_fixed = 0L, is_phenocov_fixed = 0L, diag_pheno = 0L, EM_Fels_limit = 5000L, tol = 1e-6, REML = 1L, diag_phylo = 0L) {
    .Call('_Rphylopars_EM_Fels2008', PACKAGE = 'Rphylopars', pics, vars, phylocov, phenocov, nvar, phylocov_fixed, phenocov_fixed, is_phylocov_fixed, is_phenocov_fixed, diag_pheno, EM_Fels_limit, tol, REML, diag_phylo)
}

