# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Rcpp_chol <- function(M) {
    .Call('Rphylopars_Rcpp_chol', PACKAGE = 'Rphylopars', M)
}

try_clip <- function(M, nvar, verbose) {
    .Call('Rphylopars_try_clip', PACKAGE = 'Rphylopars', M, nvar, verbose)
}

cDot <- function(A, B) {
    .Call('Rphylopars_cDot', PACKAGE = 'Rphylopars', A, B)
}

try_inv <- function(M, nvar) {
    .Call('Rphylopars_try_inv', PACKAGE = 'Rphylopars', M, nvar)
}

inv_subset <- function(mat_to_inv, subset_list) {
    .Call('Rphylopars_inv_subset', PACKAGE = 'Rphylopars', mat_to_inv, subset_list)
}

which2 <- function(x, y) {
    .Call('Rphylopars_which2', PACKAGE = 'Rphylopars', x, y)
}

condition_f <- function(iu, i, nspecies, edge, nob) {
    .Call('Rphylopars_condition_f', PACKAGE = 'Rphylopars', iu, i, nspecies, edge, nob)
}

convert_pars <- function(theta, options, T = 1) {
    .Call('Rphylopars_convert_pars', PACKAGE = 'Rphylopars', theta, options, T)
}

threepoint <- function(theta, options, y, ku, iu, edge, edgelength, uchildren_list, non_optim_transform, models, externalEdge, not_externalEdge, dist_anc, dist_des, Tmax, Tmin, nmodels, lower_bounds, upper_bounds, OU_D, times) {
    .Call('Rphylopars_threepoint', PACKAGE = 'Rphylopars', theta, options, y, ku, iu, edge, edgelength, uchildren_list, non_optim_transform, models, externalEdge, not_externalEdge, dist_anc, dist_des, Tmax, Tmin, nmodels, lower_bounds, upper_bounds, OU_D, times)
}

threepoint_nopheno <- function(theta, options, y, ku, iu, edge, edgelength, uchildren_list, edgevec, subset_list, species_subset, tip_combn, ymin, ymax, non_optim_transform, models, externalEdge, not_externalEdge, dist_anc, dist_des, Tmax, Tmin, nmodels, lower_bounds, upper_bounds, OU_D, times) {
    .Call('Rphylopars_threepoint_nopheno', PACKAGE = 'Rphylopars', theta, options, y, ku, iu, edge, edgelength, uchildren_list, edgevec, subset_list, species_subset, tip_combn, ymin, ymax, non_optim_transform, models, externalEdge, not_externalEdge, dist_anc, dist_des, Tmax, Tmin, nmodels, lower_bounds, upper_bounds, OU_D, times)
}

threepoint_phenocorr <- function(theta, options, y, ku, iu, edge, edgelength, uchildren_list, subset_list, species_subset, tip_combn, ymin, ymax, non_optim_transform, models, externalEdge, not_externalEdge, dist_anc, dist_des, Tmax, Tmin, nmodels, lower_bounds, upper_bounds, OU_D, times) {
    .Call('Rphylopars_threepoint_phenocorr', PACKAGE = 'Rphylopars', theta, options, y, ku, iu, edge, edgelength, uchildren_list, subset_list, species_subset, tip_combn, ymin, ymax, non_optim_transform, models, externalEdge, not_externalEdge, dist_anc, dist_des, Tmax, Tmin, nmodels, lower_bounds, upper_bounds, OU_D, times)
}

threepoint_calc_pheno <- function(theta, options, y, ku, iu, edge, edgelength, uchildren_list, subset_list, species_subset, tip_combn, ymin, ymax, phenocovs, inv_phenocovs, non_optim_transform, models, externalEdge, not_externalEdge, dist_anc, dist_des, Tmax, Tmin, nmodels, lower_bounds, upper_bounds, OU_D, times) {
    .Call('Rphylopars_threepoint_calc_pheno', PACKAGE = 'Rphylopars', theta, options, y, ku, iu, edge, edgelength, uchildren_list, subset_list, species_subset, tip_combn, ymin, ymax, phenocovs, inv_phenocovs, non_optim_transform, models, externalEdge, not_externalEdge, dist_anc, dist_des, Tmax, Tmin, nmodels, lower_bounds, upper_bounds, OU_D, times)
}

threepoint_predict <- function(theta, options, y, ku, iu, edge, edgelength, uchildren_list, non_optim_transform, models, externalEdge, not_externalEdge, dist_anc, dist_des, Tmax, Tmin, nmodels, lower_bounds, upper_bounds, OU_D, times) {
    .Call('Rphylopars_threepoint_predict', PACKAGE = 'Rphylopars', theta, options, y, ku, iu, edge, edgelength, uchildren_list, non_optim_transform, models, externalEdge, not_externalEdge, dist_anc, dist_des, Tmax, Tmin, nmodels, lower_bounds, upper_bounds, OU_D, times)
}

threepoint_nopheno_predict <- function(theta, options, y, ku, iu, edge, edgelength, uchildren_list, edgevec, subset_list, species_subset, tip_combn, ymin, ymax, non_optim_transform, models, externalEdge, not_externalEdge, dist_anc, dist_des, Tmax, Tmin, nmodels, lower_bounds, upper_bounds, OU_D, times) {
    .Call('Rphylopars_threepoint_nopheno_predict', PACKAGE = 'Rphylopars', theta, options, y, ku, iu, edge, edgelength, uchildren_list, edgevec, subset_list, species_subset, tip_combn, ymin, ymax, non_optim_transform, models, externalEdge, not_externalEdge, dist_anc, dist_des, Tmax, Tmin, nmodels, lower_bounds, upper_bounds, OU_D, times)
}

threepoint_phenocorr_predict <- function(theta, options, y, ku, iu, edge, edgelength, uchildren_list, subset_list, species_subset, tip_combn, ymin, ymax, non_optim_transform, models, externalEdge, not_externalEdge, dist_anc, dist_des, Tmax, Tmin, nmodels, lower_bounds, upper_bounds, OU_D, times) {
    .Call('Rphylopars_threepoint_phenocorr_predict', PACKAGE = 'Rphylopars', theta, options, y, ku, iu, edge, edgelength, uchildren_list, subset_list, species_subset, tip_combn, ymin, ymax, non_optim_transform, models, externalEdge, not_externalEdge, dist_anc, dist_des, Tmax, Tmin, nmodels, lower_bounds, upper_bounds, OU_D, times)
}

threepoint_calc_pheno_predict <- function(theta, options, y, ku, iu, edge, edgelength, uchildren_list, subset_list, species_subset, tip_combn, ymin, ymax, phenocovs, inv_phenocovs, non_optim_transform, models, externalEdge, not_externalEdge, dist_anc, dist_des, Tmax, Tmin, nmodels, lower_bounds, upper_bounds, OU_D, times) {
    .Call('Rphylopars_threepoint_calc_pheno_predict', PACKAGE = 'Rphylopars', theta, options, y, ku, iu, edge, edgelength, uchildren_list, subset_list, species_subset, tip_combn, ymin, ymax, phenocovs, inv_phenocovs, non_optim_transform, models, externalEdge, not_externalEdge, dist_anc, dist_des, Tmax, Tmin, nmodels, lower_bounds, upper_bounds, OU_D, times)
}

recursion <- function(edge, any_species_no_data, which_no_species_data, iu, options, species, tiplabel) {
    .Call('Rphylopars_recursion', PACKAGE = 'Rphylopars', edge, any_species_no_data, which_no_species_data, iu, options, species, tiplabel)
}

